"""The ``pyclawd new`` scaffolder — adopt an existing repo or start a fresh one.

Two modes, selected by whether a positional ``name`` is given:

**ADOPT** (``pyclawd new``, no positional, run inside an existing repo)
    Gather a few facts about the current project and write a
    ``./.pyclawd/config.py`` so the repo becomes pyclawd-driven. The **project
    name is taken from the current directory** (passing a positional ``name``
    instead switches to NEW-PROJECT mode); the other facts come from the
    ``--pkg`` / ``--conda-env`` / ``--tests-dir`` / ``--docs`` / ``--compile``
    options, or are prompted interactively, or — under ``--yes`` — fall back to
    inferred defaults. Nothing else is touched. Refuses to clobber an existing
    config unless ``--force``.

**NEW-PROJECT** (``pyclawd new <name>``)
    Scaffold a fresh, best-practice ``src/``-layout project under ``./<name>/``
    from the packaged templates (:mod:`pyclawd.scaffold`): ``pyproject.toml``
    (hatchling + PEP 621 + PEP 735 dev group), ``src/<pkg>/`` with ``__init__``
    and ``py.typed``, a smoke test, README/LICENSE/CHANGELOG, ``.gitignore``,
    ``.python-version``, a GitHub Actions CI workflow, and a ``.pyclawd/config.py``
    so the project is pyclawd-driven from commit zero. Refuses to clobber an
    existing directory unless ``--force``.

The skeleton files come from ``*.tmpl`` templates rendered with simple
``{{placeholder}}`` substitution. The ``.pyclawd/config.py`` is generated by
:func:`_render_config` (rather than a template) because its shape varies with the
answers (conda env, docs, compile step).
"""

from __future__ import annotations

import datetime
import subprocess
from importlib.resources import files
from pathlib import Path

import typer

from .skills import DEFAULT_TARGET, bundled_skill_names, install_skills

# Template file name -> output path (relative to the project root). ``{pkg}`` in
# an output path is filled with the package import name. Template files use safe,
# non-dotted names so they ship cleanly in the wheel; the real (often dotted)
# destination name lives here.
_SKELETON: dict[str, str] = {
    "pyproject.toml.tmpl": "pyproject.toml",
    "README.md.tmpl": "README.md",
    "LICENSE.tmpl": "LICENSE",
    "CHANGELOG.md.tmpl": "CHANGELOG.md",
    "gitignore.tmpl": ".gitignore",
    "python-version.tmpl": ".python-version",
    "ci.yml.tmpl": ".github/workflows/ci.yml",
    "init.py.tmpl": "src/{pkg}/__init__.py",
    "py.typed.tmpl": "src/{pkg}/py.typed",
    "test_smoke.py.tmpl": "tests/test_smoke.py",
}


# --------------------------------------------------------------------------- #
# Small helpers.
# --------------------------------------------------------------------------- #


def _templates_dir():
    """Return the packaged ``templates/`` directory as an importlib Traversable."""
    return files("pyclawd.scaffold") / "templates"


def _render(text: str, ctx: dict[str, str]) -> str:
    """Substitute every ``{{key}}`` in *text* with ``ctx[key]``.

    Unknown ``{{...}}`` spans (e.g. GitHub Actions' ``${{ matrix... }}``) are left
    untouched because only the explicit keys in *ctx* are replaced.

    Parameters
    ----------
    text : str
        Template body.
    ctx : dict of str to str
        Placeholder name -> replacement value.

    Returns
    -------
    str
        The rendered text.
    """
    for key, value in ctx.items():
        text = text.replace("{{" + key + "}}", value)
    return text


def _default_pkg(name: str) -> str:
    """Derive a valid package import name from a project *name* (``-`` -> ``_``)."""
    return name.strip().replace("-", "_").replace(" ", "_")


def _git_config(key: str, fallback: str) -> str:
    """Return ``git config --get <key>`` if available, else *fallback*."""
    try:
        out = subprocess.run(
            ["git", "config", "--get", key],
            capture_output=True,
            text=True,
            check=False,
        )
        value = out.stdout.strip()
        return value or fallback
    except (OSError, subprocess.SubprocessError):
        return fallback


def _write(path: Path, content: str) -> None:
    """Create parent dirs and write *content* to *path* (UTF-8)."""
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")


# --------------------------------------------------------------------------- #
# Agent-readiness — AGENTS.md / CLAUDE.md + bundled skills (both modes).
# --------------------------------------------------------------------------- #


def _write_agent_guide(root: Path, ctx: dict[str, str]) -> None:
    """Write ``AGENTS.md`` (from the template) and a tiny ``CLAUDE.md`` into *root*.

    Existing files are never clobbered — a note is printed instead — so this is
    safe to run when adopting a repo that already has agent docs.
    """
    agents = root / "AGENTS.md"
    if agents.exists():
        typer.secho(f"note: {agents.name} exists — leaving it untouched.", fg="yellow")
    else:
        body = _render((_templates_dir() / "AGENTS.md.tmpl").read_text(encoding="utf-8"), ctx)
        _write(agents, body)
        typer.secho("✓ wrote AGENTS.md", fg="green")

    claude = root / "CLAUDE.md"
    if claude.exists():
        typer.secho(f"note: {claude.name} exists — leaving it untouched.", fg="yellow")
    else:
        _write(claude, "@AGENTS.md\n")
        typer.secho("✓ wrote CLAUDE.md", fg="green")


def _install_project_skills(root: Path) -> None:
    """Install the bundled ``pyclawd-*`` skills into ``<root>/.claude/skills/``."""
    installed, skipped = install_skills(root / DEFAULT_TARGET, force=False)
    if installed:
        typer.secho(
            f"✓ installed {len(installed)} skill(s) into {DEFAULT_TARGET}: " + ", ".join(installed),
            fg="green",
        )
    if skipped:
        typer.secho(
            f"  · {len(skipped)} skill(s) already present (use --force to refresh)",
            fg="bright_black",
        )
    if not bundled_skill_names():
        typer.secho("note: no bundled skills found to install.", fg="yellow")


# --------------------------------------------------------------------------- #
# .pyclawd/config.py generation (used by both modes).
# --------------------------------------------------------------------------- #


def _render_config(
    *,
    name: str,
    pkg: str,
    conda_env: str | None,
    tests_dir: str,
    docs: bool,
    compile_step: bool,
) -> str:
    """Build the source text of a ``.pyclawd/config.py`` for a project.

    Mirrors the shape of pyclawd's own dogfood config: a module-level
    ``project = Project(...)`` with a :class:`~pyclawd.QualityConfig` (ruff +
    mypy), a :class:`~pyclawd.TestConfig`, and a :class:`~pyclawd.DoctorConfig`.
    Optional ``docs`` / ``compile_step`` add the corresponding blocks.

    Parameters
    ----------
    name : str
        Project name.
    pkg : str
        Package import name.
    conda_env : str or None
        Conda env the project expects, or ``None`` for env-agnostic.
    tests_dir : str
        Root-relative tests directory (e.g. ``"tests/"``).
    docs : bool
        Whether to include a :class:`~pyclawd.DocsConfig` block.
    compile_step : bool
        Whether to include a build/compile step.

    Returns
    -------
    str
        The full text of the config module.
    """
    imports = ["DoctorConfig", "Project", "QualityConfig", "TestConfig"]
    if docs:
        imports.append("DocsConfig")
    imports_line = ", ".join(sorted(imports))

    conda_repr = "None" if not conda_env else repr(conda_env)

    build_block = ""
    if compile_step:
        build_block = (
            '    compile_cmd=["setup.py", "build_ext", "--inplace"],\n'
            '    clean_targets=["build", "dist"],\n'
        )

    docs_block = ""
    if docs:
        docs_block = (
            "    # NOTE: `runner` must point at a docs toolchain you provide (an\n"
            "    # isolated ./docs project exposing build/run/compile/exec/clean —\n"
            "    # typically sphinx + nbsphinx + jupyter-cache). pyclawd does NOT\n"
            "    # scaffold it; `pyclawd docs` reports 'not configured' until it exists.\n"
            "    docs=DocsConfig(\n"
            '        runner=["uvx", "--from", "./docs", "docs"],\n'
            '        source_dir="docs/source",\n'
            '        cache_dir="docs/.jupyter_cache",\n'
            '        cache_db="docs/.jupyter_cache/global.db",\n'
            '        build_html="docs/build/html",\n'
            '        branch="main",\n'
            "    ),\n"
        )

    return (
        f'"""{name}\'s pyclawd config — drives `pyclawd test/lint/typecheck/...`'
        " for this repo.\n"
        '"""\n\n'
        f"from pyclawd import {imports_line}\n\n"
        "project = Project(\n"
        f"    name={name!r},\n"
        f"    conda_env={conda_repr},\n"
        '    root_markers=["pyproject.toml"],\n'
        "    # Default directory `pyclawd ls` lists (the code/source root).\n"
        '    src_dir="src",\n'
        f"{build_block}"
        "    quality=QualityConfig(\n"
        '        lint_cmd=["ruff", "check"],\n'
        '        lint_fix_cmd=["ruff", "check", "--fix"],\n'
        '        format_cmd=["ruff", "format"],\n'
        '        format_check_cmd=["ruff", "format", "--check"],\n'
        '        typecheck_cmd=["mypy", "src"],\n'
        '        check_sequence=["format-check", "lint", "typecheck", "test"],\n'
        "    ),\n"
        "    test=TestConfig(\n"
        f"        tests_dir={tests_dir!r},\n"
        '        classname_prefix="tests.",\n'
        "        integration_files=[],\n"
        '        markers={"default": "not slow", "fast": "not slow", "all": ""},\n'
        "    ),\n"
        f"{docs_block}"
        "    doctor=DoctorConfig(\n"
        "        core_deps=[],\n"
        '        dev_deps=["pytest"],\n'
        "        tool_files=[],\n"
        "        binaries=[\n"
        '            ("ruff", "pip install ruff"),\n'
        '            ("mypy", "pip install mypy"),\n'
        "        ],\n"
        "    ),\n"
        ")\n"
    )


# --------------------------------------------------------------------------- #
# ADOPT mode.
# --------------------------------------------------------------------------- #


def _ask(value: str | None, prompt: str, default: str, interactive: bool) -> str:
    """Resolve a string answer: explicit *value*, else prompt, else *default*."""
    if value is not None:
        return value
    if interactive:
        return str(typer.prompt(prompt, default=default))
    return default


def _ask_bool(value: bool | None, prompt: str, default: bool, interactive: bool) -> bool:
    """Resolve a yes/no answer: explicit *value*, else confirm, else *default*."""
    if value is not None:
        return value
    if interactive:
        return bool(typer.confirm(prompt, default=default))
    return default


def _adopt(
    *,
    force: bool,
    name: str | None,
    pkg: str | None,
    conda_env: str | None,
    tests_dir: str | None,
    docs: bool | None,
    compile_step: bool | None,
    yes: bool,
    no_agent: bool = False,
    no_skills: bool = False,
) -> None:
    """Write a ``./.pyclawd/config.py`` for the current repository.

    The project name defaults to the **current directory name** (there is no
    ``--name`` flag in adopt mode — a positional name switches to NEW-PROJECT
    mode); under interactive mode it can still be edited at the prompt. Every
    other value comes from the matching option when given; otherwise it is
    prompted (unless ``--yes``, which accepts the inferred defaults). Refuses to
    overwrite an existing config unless ``force``. After writing the config, also
    offers to land agent-readiness (``AGENTS.md`` + bundled skills) — on by
    default, skippable with ``--no-agent`` / ``--no-skills``.
    """
    cwd = Path.cwd()
    target = cwd / ".pyclawd" / "config.py"
    if target.exists() and not force:
        typer.secho(
            f"refusing to overwrite {target} — pass --force to replace it.",
            fg="red",
            err=True,
        )
        raise typer.Exit(1)

    interactive = not yes
    name_v = _ask(name, "Project name", cwd.name, interactive)
    pkg_v = _ask(pkg, "Package import name", _default_pkg(name_v), interactive)
    env_v = _ask(conda_env, "Conda env (blank = none)", "", interactive)
    tests_v = _ask(tests_dir, "Tests directory", "tests/", interactive)
    docs_v = _ask_bool(docs, "Does this project build docs?", False, interactive)
    compile_v = _ask_bool(
        compile_step, "Does this project have a build/compile step?", False, interactive
    )

    content = _render_config(
        name=name_v,
        pkg=pkg_v,
        conda_env=env_v or None,
        tests_dir=tests_v,
        docs=docs_v,
        compile_step=compile_v,
    )
    _write(target, content)
    typer.secho(f"✓ wrote {target.relative_to(cwd)}", fg="green")

    # Agent-readiness — offer (default yes), skippable, scriptable.
    ctx = {
        "name": name_v,
        "pkg": pkg_v,
        "owner": _default_pkg(_git_config("user.name", "your-org")).lower() or "your-org",
    }
    if not no_agent and _ask_bool(
        None, "Write AGENTS.md + CLAUDE.md agent guide?", True, interactive
    ):
        _write_agent_guide(cwd, ctx)
    if not no_skills and _ask_bool(
        None, "Install bundled pyclawd skills into .claude/skills/?", True, interactive
    ):
        _install_project_skills(cwd)

    typer.echo("\nNext steps:")
    typer.echo("  pyclawd root        # confirm pyclawd now resolves this repo")
    typer.echo("  pyclawd doctor      # health-check the dev env")
    typer.echo("  pyclawd test        # run the test suite")
    if docs_v:
        typer.secho(
            "\nNote: docs is enabled but pyclawd does not scaffold the ./docs runner.\n"
            "  Provide an isolated docs toolchain (sphinx + nbsphinx + jupyter-cache)\n"
            "  matching `project.docs.runner`, or `pyclawd docs` stays unconfigured.",
            fg="yellow",
        )


# --------------------------------------------------------------------------- #
# NEW-PROJECT mode.
# --------------------------------------------------------------------------- #


def _new_project(
    *,
    name: str,
    force: bool,
    pkg: str | None,
    author: str,
    email: str,
    no_agent: bool = False,
    no_skills: bool = False,
) -> None:
    """Scaffold a fresh best-practice project under ``./<name>/``.

    Renders every template in :data:`_SKELETON` plus a generated
    ``.pyclawd/config.py``, then (unless opted out) lands agent-readiness: an
    ``AGENTS.md`` + ``CLAUDE.md`` guide and the bundled skills under
    ``<name>/.claude/skills/``. Refuses to write into an existing, non-empty
    target unless ``force``.
    """
    dest = Path.cwd() / name
    if dest.exists() and any(dest.iterdir()) and not force:
        typer.secho(
            f"refusing to scaffold into existing non-empty {dest} — pass --force.",
            fg="red",
            err=True,
        )
        raise typer.Exit(1)

    pkg_v = pkg or _default_pkg(name)
    ctx = {
        "name": name,
        "pkg": pkg_v,
        "author": author,
        "email": email,
        "owner": _default_pkg(author).lower() or "your-org",
        "year": str(datetime.date.today().year),
        "description": f"{name} — a Python project.",
    }

    tdir = _templates_dir()
    for tmpl_name, out_rel in _SKELETON.items():
        body = (tdir / tmpl_name).read_text(encoding="utf-8")
        rendered = _render(body, ctx)
        out_path = dest / out_rel.format(pkg=pkg_v)
        _write(out_path, rendered)

    config = _render_config(
        name=name,
        pkg=pkg_v,
        conda_env=None,
        tests_dir="tests/",
        docs=False,
        compile_step=False,
    )
    _write(dest / ".pyclawd" / "config.py", config)

    # Agent-readiness: make the fresh project Claude-Code-ready out of the box.
    if not no_agent:
        _write_agent_guide(dest, ctx)
    if not no_skills:
        _install_project_skills(dest)

    typer.secho(f"✓ scaffolded {name} at {dest}", fg="green")
    typer.echo("\nNext steps:")
    typer.echo(f"  cd {name}")
    typer.echo("  git init && git add -A && git commit -m 'Initial commit'")
    typer.echo("  pip install -e . --group dev")
    typer.echo("  pyclawd check       # format-check -> lint -> typecheck -> test")


# --------------------------------------------------------------------------- #
# The command + registration.
# --------------------------------------------------------------------------- #


def new(
    name: str = typer.Argument(
        None,
        help="New project name. Omit to ADOPT the current repo (write ./.pyclawd/config.py).",
    ),
    force: bool = typer.Option(False, "--force", help="Overwrite an existing target/config."),
    pkg: str = typer.Option(None, "--pkg", help="Package import name (default: name with - -> _)."),
    author: str = typer.Option(
        None, "--author", help="Author name for new-project metadata (default: git user.name)."
    ),
    email: str = typer.Option(
        None, "--email", help="Author email for new-project metadata (default: git user.email)."
    ),
    conda_env: str = typer.Option(
        None, "--conda-env", help="ADOPT: conda env the project runs in (blank = none)."
    ),
    tests_dir: str = typer.Option(None, "--tests-dir", help="ADOPT: tests directory."),
    docs: bool = typer.Option(None, "--docs/--no-docs", help="ADOPT: does the project build docs?"),
    compile_step: bool = typer.Option(
        None, "--compile/--no-compile", help="ADOPT: does the project have a build step?"
    ),
    yes: bool = typer.Option(
        False, "--yes", "-y", help="ADOPT: non-interactive — accept inferred defaults."
    ),
    no_agent: bool = typer.Option(
        False, "--no-agent", help="Do not write AGENTS.md / CLAUDE.md agent guide."
    ),
    no_skills: bool = typer.Option(
        False, "--no-skills", help="Do not install the bundled pyclawd skills."
    ),
) -> None:
    """Scaffold a new project (``pyclawd new <name>``) or adopt the current repo."""
    if name is None:
        _adopt(
            force=force,
            name=None,
            pkg=pkg,
            conda_env=conda_env,
            tests_dir=tests_dir,
            docs=docs,
            compile_step=compile_step,
            yes=yes,
            no_agent=no_agent,
            no_skills=no_skills,
        )
        return

    _new_project(
        name=name,
        force=force,
        pkg=pkg,
        author=author or _git_config("user.name", "Your Name"),
        email=email or _git_config("user.email", "you@example.com"),
        no_agent=no_agent,
        no_skills=no_skills,
    )


def register(app: typer.Typer) -> None:
    """Attach the ``new`` command to *app*."""
    app.command()(new)
