"""Tests for the golden pytest plugin (key derivation, the auto-id guardrail, roundtrip)."""

from __future__ import annotations

import textwrap

import pytest

from pyclawd.pytest_plugin import (
    DEFAULT_MARKER,
    GoldenIdWarning,
    _argnames_from_spec,
    derive_node_key,
    looks_autogenerated,
    param_id,
)

pytest_plugins = ["pytester"]


# --------------------------------------------------------------------------- #
# Pure helpers — node-key derivation.
# --------------------------------------------------------------------------- #


@pytest.mark.parametrize(
    ("nodeid", "expected"),
    [
        ("tests/test_x.py::test_f", "test_f"),
        ("tests/test_x.py::test_f[zdt1-de]", "test_f[zdt1-de]"),
        ("tests/test_x.py::TestC::test_f[3]", "test_f[3]"),
        ("test_f", "test_f"),
    ],
)
def test_derive_node_key(nodeid: str, expected: str) -> None:
    assert derive_node_key(nodeid) == expected


@pytest.mark.parametrize(
    ("node_key", "expected"),
    [
        ("test_f", None),
        ("test_f[zdt1-de]", "zdt1-de"),
        ("test_f[algo0]", "algo0"),
        ("test_f[a-b-c]", "a-b-c"),
    ],
)
def test_param_id(node_key: str, expected: str | None) -> None:
    assert param_id(node_key) == expected


# --------------------------------------------------------------------------- #
# Pure helpers — the auto-id guardrail.
# --------------------------------------------------------------------------- #


@pytest.mark.parametrize(
    ("pid", "argnames"),
    [
        ("algorithm0", {"algorithm"}),
        ("problem1", {"problem"}),
        ("algo10", {"algo"}),
        # An auto segment alongside an explicit one in a multi-arg id.
        ("zdt1-algorithm0", {"algorithm"}),
        ("problem0-algorithm1", {"problem", "algorithm"}),
    ],
)
def test_looks_autogenerated_flags_index_based(pid: str, argnames: set[str]) -> None:
    assert looks_autogenerated(pid, argnames) is True


@pytest.mark.parametrize(
    ("pid", "argnames"),
    [
        # Explicit ids whose argnames are excluded (ids= was supplied) → empty set.
        ("s1", set()),
        ("s2", set()),
        # Explicit ids whose prefix is not a parametrize argname.
        ("zdt1", {"problem"}),
        ("dtlz2", {"problem"}),
        ("nsga2", {"algorithm"}),
        # Readable non-numeric ids.
        ("de", {"algorithm"}),
        ("zdt-de", {"problem", "algorithm"}),
        # Argname matches the prefix but no trailing digits → not auto.
        ("algorithm", {"algorithm"}),
    ],
)
def test_looks_autogenerated_passes_explicit(pid: str, argnames: set[str]) -> None:
    assert looks_autogenerated(pid, argnames) is False


@pytest.mark.parametrize(
    ("spec", "expected"),
    [
        ("seed", ["seed"]),
        ("a,b", ["a", "b"]),
        (" a , b ", ["a", "b"]),
        (["x", "y"], ["x", "y"]),
        (("x", "y"), ["x", "y"]),
        (123, []),
    ],
)
def test_argnames_from_spec(spec: object, expected: list[str]) -> None:
    assert _argnames_from_spec(spec) == expected


# --------------------------------------------------------------------------- #
# Integration — record then compare against a real temp pyclawd project.
# --------------------------------------------------------------------------- #

_CONFIG = textwrap.dedent(
    """
    from pyclawd import DoctorConfig, GoldenConfig, Project, TestConfig

    project = Project(
        name="tmpgold",
        conda_env=None,
        root_markers=[],
        test=TestConfig(
            tests_dir="tests",
            classname_prefix="tests.",
            integration_files=[],
            markers={"default": "", "fast": "", "all": ""},
        ),
        doctor=DoctorConfig(core_deps=[], dev_deps=[], tool_files=[], binaries=[]),
        golden=GoldenConfig(),
    )
    """
)

_TEST_PASS = textwrap.dedent(
    """
    import pytest

    @pytest.mark.golden
    def test_value(golden):
        golden(3.14159)
    """
)

# Different string length than 3.14159 so Python's mtime+size .pyc invalidation
# is guaranteed to recompile the rewritten module on the gate run.
_TEST_DRIFT = _TEST_PASS.replace("3.14159", "42.0")


def _scaffold(pytester: pytest.Pytester, test_src: str) -> None:
    """Write a minimal pyclawd project (config + golden test) into the pytester dir."""
    cfg_dir = pytester.path / ".pyclawd"
    cfg_dir.mkdir(exist_ok=True)
    (cfg_dir / "config.py").write_text(_CONFIG)
    pytester.makepyfile(test_demo=test_src)


def _run(pytester: pytest.Pytester) -> pytest.RunResult:
    """Run the golden tier in a clean subprocess with the plugin loaded explicitly.

    ``-p no:cacheprovider`` and a no-bytecode env keep each run reading source
    fresh, so a rewritten test module is never served from a stale ``.pyc``.
    """
    return pytester.runpytest_subprocess(
        "-p", "pyclawd.pytest_plugin", "-m", "golden", "-p", "no:cacheprovider"
    )


def test_record_then_compare_roundtrip(
    pytester: pytest.Pytester, monkeypatch: pytest.MonkeyPatch
) -> None:
    monkeypatch.delenv("PYCLAWD_CONFIG", raising=False)
    _scaffold(pytester, _TEST_PASS)

    # 1. Update mode records the baseline.
    monkeypatch.setenv("PYCLAWD_GOLDEN_UPDATE", "1")
    _run(pytester).assert_outcomes(passed=1)
    baseline = pytester.path / "tests" / "golden" / "test_demo.json"
    assert baseline.is_file(), "update mode should have written the module baseline"
    assert "test_value" in baseline.read_text()

    # 2. Gate mode compares against the committed baseline and passes.
    monkeypatch.delenv("PYCLAWD_GOLDEN_UPDATE", raising=False)
    _run(pytester).assert_outcomes(passed=1)


def test_gate_fails_on_drift(pytester: pytest.Pytester, monkeypatch: pytest.MonkeyPatch) -> None:
    monkeypatch.delenv("PYCLAWD_CONFIG", raising=False)
    monkeypatch.setenv("PYTHONDONTWRITEBYTECODE", "1")
    _scaffold(pytester, _TEST_PASS)

    monkeypatch.setenv("PYCLAWD_GOLDEN_UPDATE", "1")
    _run(pytester).assert_outcomes(passed=1)

    # Change the observable value; gate mode must catch the drift.
    monkeypatch.delenv("PYCLAWD_GOLDEN_UPDATE", raising=False)
    pytester.makepyfile(test_demo=_TEST_DRIFT)
    _run(pytester).assert_outcomes(failed=1)


def test_fixture_fails_without_golden_config(
    pytester: pytest.Pytester, monkeypatch: pytest.MonkeyPatch
) -> None:
    monkeypatch.delenv("PYCLAWD_CONFIG", raising=False)
    monkeypatch.delenv("PYCLAWD_GOLDEN_UPDATE", raising=False)
    cfg_dir = pytester.path / ".pyclawd"
    cfg_dir.mkdir(exist_ok=True)
    (cfg_dir / "config.py").write_text(_CONFIG.replace("golden=GoldenConfig(),", ""))
    pytester.makepyfile(test_demo=_TEST_PASS)
    result = pytester.runpytest_subprocess("-p", "pyclawd.pytest_plugin")
    # A fixture raising pytest.fail is reported as a setup error, not a failure.
    result.assert_outcomes(errors=1)
    result.stdout.fnmatch_lines(["*golden not configured*"])


# Reproduces the coordinator's bug: explicit ids ``s1``/``s2`` must NOT warn.
_TEST_EXPLICIT_IDS = textwrap.dedent(
    """
    import pytest

    @pytest.mark.golden
    @pytest.mark.parametrize("seed", [1, 2], ids=["s1", "s2"])
    def test_seeded(golden, seed):
        golden(float(seed))
    """
)

# Object params with no ids= → pytest auto-numbers as ``algorithm0``/``algorithm1``.
_TEST_AUTO_IDS = textwrap.dedent(
    """
    import pytest

    @pytest.mark.golden
    @pytest.mark.parametrize("algorithm", [object(), object()])
    def test_algo(golden, algorithm):
        golden(1.0)
    """
)


def test_explicit_ids_do_not_warn(
    pytester: pytest.Pytester, monkeypatch: pytest.MonkeyPatch
) -> None:
    monkeypatch.delenv("PYCLAWD_CONFIG", raising=False)
    monkeypatch.setenv("PYCLAWD_GOLDEN_UPDATE", "1")
    cfg_dir = pytester.path / ".pyclawd"
    cfg_dir.mkdir(exist_ok=True)
    (cfg_dir / "config.py").write_text(_CONFIG)
    pytester.makepyfile(test_demo=_TEST_EXPLICIT_IDS)
    result = _run(pytester)
    result.assert_outcomes(passed=2)
    assert "GoldenIdWarning" not in result.stdout.str()


def test_auto_numbered_ids_warn(pytester: pytest.Pytester, monkeypatch: pytest.MonkeyPatch) -> None:
    monkeypatch.delenv("PYCLAWD_CONFIG", raising=False)
    monkeypatch.setenv("PYCLAWD_GOLDEN_UPDATE", "1")
    cfg_dir = pytester.path / ".pyclawd"
    cfg_dir.mkdir(exist_ok=True)
    (cfg_dir / "config.py").write_text(_CONFIG)
    pytester.makepyfile(test_demo=_TEST_AUTO_IDS)
    result = _run(pytester)
    result.assert_outcomes(passed=2)
    result.stdout.fnmatch_lines(["*GoldenIdWarning*"])


def test_default_marker_is_golden() -> None:
    assert DEFAULT_MARKER == "golden"
    assert issubclass(GoldenIdWarning, UserWarning)
