"""Tests for the golden pytest plugin (key derivation, the auto-id guardrail, return capture)."""

from __future__ import annotations

import json
import textwrap

import pytest

from pyclawd.pytest_plugin import (
    GoldenIdWarning,
    _argnames_from_spec,
    derive_node_key,
    looks_autogenerated,
    param_id,
)

pytest_plugins = ["pytester"]


# --------------------------------------------------------------------------- #
# Pure helpers — node-key derivation.
# --------------------------------------------------------------------------- #


@pytest.mark.parametrize(
    ("nodeid", "expected"),
    [
        ("tests/t.py::test_f[zdt1-de]", "test_f[zdt1-de]"),
        ("tests/test_x.py::test_f", "test_f"),
        ("tests/test_x.py::TestC::test_f[3]", "test_f[3]"),
        ("test_f", "test_f"),
    ],
)
def test_derive_node_key(nodeid: str, expected: str) -> None:
    assert derive_node_key(nodeid) == expected


@pytest.mark.parametrize(
    ("node_key", "expected"),
    [
        ("test_f", None),
        ("test_f[zdt1-de]", "zdt1-de"),
        ("test_f[algo0]", "algo0"),
        ("test_f[a-b-c]", "a-b-c"),
    ],
)
def test_param_id(node_key: str, expected: str | None) -> None:
    assert param_id(node_key) == expected


@pytest.mark.parametrize(
    ("spec", "expected"),
    [
        ("seed", ["seed"]),
        ("a,b", ["a", "b"]),
        (" a , b ", ["a", "b"]),
        (["x", "y"], ["x", "y"]),
        (("x", "y"), ["x", "y"]),
        (123, []),
        (None, []),
    ],
)
def test_argnames_from_spec(spec: object, expected: list[str]) -> None:
    assert _argnames_from_spec(spec) == expected


# --------------------------------------------------------------------------- #
# Pure helpers — the auto-id guardrail.
# --------------------------------------------------------------------------- #


@pytest.mark.parametrize(
    ("pid", "argnames"),
    [
        ("algorithm0", {"algorithm"}),
        ("problem1", {"problem"}),
        ("algo10", {"algo"}),
        # An auto segment alongside an explicit one in a multi-arg id.
        ("zdt1-algorithm0", {"algorithm"}),
    ],
)
def test_looks_autogenerated_flags_index_based(pid: str, argnames: set[str]) -> None:
    assert looks_autogenerated(pid, argnames) is True


@pytest.mark.parametrize(
    ("pid", "argnames"),
    [
        # Explicit ids whose argnames are excluded (ids= was supplied) → empty set.
        ("s1", set()),
        ("s2", set()),
        # Explicit ids whose prefix is not a parametrize argname.
        ("zdt1", {"problem"}),
        ("dtlz2", {"problem"}),
        ("nsga2", {"algorithm"}),
        # Readable non-numeric id.
        ("de", {"algorithm"}),
        # Argname matches the prefix but no trailing digits → not auto.
        ("algorithm", {"algorithm"}),
    ],
)
def test_looks_autogenerated_passes_explicit(pid: str, argnames: set[str]) -> None:
    assert looks_autogenerated(pid, argnames) is False


def test_golden_id_warning_is_user_warning() -> None:
    assert issubclass(GoldenIdWarning, UserWarning)


# --------------------------------------------------------------------------- #
# End-to-end via pytester — return capture, record, compare, drift.
# --------------------------------------------------------------------------- #

_DEMO = textwrap.dedent(
    """
    import numpy as np
    import pytest

    @pytest.mark.golden
    def test_s():
        return 2.5

    @pytest.mark.golden
    def test_a():
        return np.array([1.0, 2.0, 3.0])
    """
)

# A float drift in test_s only; test_a is unchanged.
_DEMO_DRIFT = _DEMO.replace("return 2.5", "return 9.9")

_DEMO_SINGLE = textwrap.dedent(
    """
    import pytest

    @pytest.mark.golden
    def test_s():
        return 2.5
    """
)


def _scaffold(pytester: pytest.Pytester, src: str = _DEMO) -> None:
    """Write a pytester sub-config (golden_dir) and a golden test module."""
    pytester.makeini("[pytest]\ngolden_dir = tests/golden\n")
    pytester.makepyfile(test_demo=src)


def _run(pytester: pytest.Pytester, *args: str) -> pytest.RunResult:
    """Run pytest in a clean subprocess so the plugin and numpy load cleanly.

    The plugin self-registers through its ``pytest11`` entry point, so the
    subprocess picks it up automatically; ``no:cacheprovider`` keeps each run
    reading the source fresh after a rewrite.
    """
    return pytester.runpytest_subprocess("-p", "no:cacheprovider", *args)


def test_update_records_baseline(pytester: pytest.Pytester) -> None:
    _scaffold(pytester)
    _run(pytester, "--golden-update").assert_outcomes(passed=2)

    path = pytester.path / "tests" / "golden" / "test_demo.json"
    assert path.is_file(), "update mode should have written the module baseline"

    text = path.read_text()
    assert "blessed_on" not in text
    data = json.loads(text)
    assert data["test_s"]["value"] == 2.5
    assert data["test_a"]["value"] == [1.0, 2.0, 3.0]


def test_compare_passes_against_baseline(pytester: pytest.Pytester) -> None:
    _scaffold(pytester)
    _run(pytester, "--golden-update").assert_outcomes(passed=2)
    # Compare mode hits the just-recorded baseline.
    _run(pytester).assert_outcomes(passed=2)


def test_compare_detects_drift(pytester: pytest.Pytester, monkeypatch: pytest.MonkeyPatch) -> None:
    monkeypatch.setenv("PYTHONDONTWRITEBYTECODE", "1")
    _scaffold(pytester)
    _run(pytester, "--golden-update").assert_outcomes(passed=2)

    # Rewrite test_s to drift; test_a stays on baseline.
    pytester.makepyfile(test_demo=_DEMO_DRIFT)
    result = _run(pytester)
    result.assert_outcomes(failed=1, passed=1)
    assert "test_s" in result.stdout.str()


def test_compare_without_baseline_fails(pytester: pytest.Pytester) -> None:
    pytester.makeini("[pytest]\ngolden_dir = tests/golden\n")
    pytester.makepyfile(test_demo=_DEMO_SINGLE)
    result = _run(pytester)
    result.assert_outcomes(failed=1)
    assert "no baseline" in result.stdout.str()
