"""Standalone pytest plugin: a ``@pytest.mark.golden`` test's return value is the snapshot.

Tag a test ``@pytest.mark.golden``; whatever it **returns** is captured and, based
on its type, recorded to / compared against a committed baseline under
``tests/golden/<module>.json``. A ``float`` stores as a readable rounded number, an
``np.ndarray`` as a readable nested list — so a ``git diff`` of a baseline shows
exactly which numbers moved. ``pytest --golden-update`` (re)records baselines for a
human to review and commit; the default run compares and fails on drift.

This plugin is **standalone** — it depends only on the dependency-free
:mod:`pyclawd.golden` engine, never on a ``.pyclawd/config.py`` or any pyclawd
project. An adopting project installs pyclawd, and the ``golden`` marker + the
return-capture behaviour work in bare ``pytest`` with zero config (the plugin
registers via a ``pytest11`` entry point). All settings have defaults and are
overridable through standard pytest ini options (``golden_dir``, ``golden_marker``,
``golden_rtol``, ``golden_atol``, ``golden_precision``).

Doctrine (see :mod:`pyclawd.golden`): tolerance is the gate, the stored hash is only
a fast path; *agents compare, humans bless*.
"""

from __future__ import annotations

import warnings
from collections.abc import Iterable
from pathlib import Path
from typing import Any

import pytest

from pyclawd.golden import GoldenError, GoldenStore, compare, make_entry, module_baseline_path

#: Default marker / baseline directory when nothing is configured.
DEFAULT_MARKER = "golden"
DEFAULT_DIR = "tests/golden"


class GoldenIdWarning(UserWarning):
    """A golden snapshot key is built from an auto-generated parametrize id.

    Index-based ids (e.g. ``algorithm0``) silently shift when parametrize cases
    are added or reordered, which would orphan committed baselines. Emitted as a
    nudge to pin explicit ``ids=`` on the parametrize.
    """


# --------------------------------------------------------------------------- #
# Snapshot-key derivation + the parametrize-id guardrail (pure, no pytest state).
# --------------------------------------------------------------------------- #


def derive_node_key(nodeid: str) -> str:
    """Derive the snapshot key from a pytest node id (its last ``::`` segment).

    Args:
        nodeid: The pytest node id (e.g. ``tests/test_x.py::test_f[zdt1-de]``).

    Returns:
        The function name including any ``[param]`` suffix — the stable per-case key.
    """
    return nodeid.split("::")[-1]


def param_id(node_key: str) -> str | None:
    """Extract the bracketed parametrization id from a node key, if any.

    Args:
        node_key: A key from :func:`derive_node_key`.

    Returns:
        The text inside ``[...]`` (e.g. ``"zdt1-de"``), or ``None`` if unparametrized.
    """
    if "[" not in node_key:
        return None
    return node_key.split("[", 1)[1].rsplit("]", 1)[0]


def _argnames_from_spec(spec: object) -> list[str]:
    """Normalise a ``parametrize`` argname spec (``"a,b"`` or ``["a","b"]``) into names."""
    if isinstance(spec, str):
        return [name.strip() for name in spec.split(",") if name.strip()]
    if isinstance(spec, (list, tuple)):
        return [str(name).strip() for name in spec if str(name).strip()]
    return []


def auto_argnames(node: pytest.Item) -> set[str]:
    """Argnames whose ids pytest may auto-number for this test node.

    Only ``parametrize`` marks without an explicit ``ids=`` can produce the fragile
    ``<argname><index>`` form; a mark with ``ids=`` owns its ids and is excluded.

    Args:
        node: The running pytest item.

    Returns:
        Argnames eligible for auto-numbered ids.
    """
    names: set[str] = set()
    for mark in node.iter_markers("parametrize"):
        if mark.kwargs.get("ids") is not None:
            continue
        if mark.args:
            names.update(_argnames_from_spec(mark.args[0]))
    return names


def looks_autogenerated(pid: str, argnames: Iterable[str]) -> bool:
    """Whether a parametrize id is an index-based ``<argname><digits>`` (pytest-auto).

    An explicit id whose text merely ends in a digit (``zdt1``, ``nsga2``, ``s2``)
    is **not** flagged, because its prefix is not a parametrize argname.

    Args:
        pid: The parametrization id (text between ``[`` and ``]``).
        argnames: Argnames eligible for auto-numbering (see :func:`auto_argnames`).

    Returns:
        ``True`` if any ``-``-separated segment is an ``<argname><digits>``.
    """
    argset = set(argnames)
    if not argset:
        return False
    for seg in pid.split("-"):
        for name in argset:
            tail = seg[len(name) :]
            if seg.startswith(name) and tail.isdigit():
                return True
    return False


# --------------------------------------------------------------------------- #
# pytest hooks — config, marker, and the return-value capture.
# --------------------------------------------------------------------------- #


def pytest_addoption(parser: pytest.Parser) -> None:
    """Register the ``--golden-update`` flag and the ``golden_*`` ini settings."""
    parser.addoption(
        "--golden-update",
        action="store_true",
        default=False,
        help="Record/bless golden baselines from test return values instead of comparing.",
    )
    parser.addini(
        "golden_dir", "Directory holding committed golden baselines.", default=DEFAULT_DIR
    )
    parser.addini("golden_marker", "Marker selecting golden tests.", default=DEFAULT_MARKER)
    parser.addini("golden_precision", "Default decimal places for float rounding.", default="10")
    parser.addini("golden_rtol", "Default relative tolerance.", default="1e-9")
    parser.addini("golden_atol", "Default absolute tolerance.", default="1e-12")


def _marker(config: pytest.Config) -> str:
    """The configured golden marker name (default ``golden``)."""
    return str(config.getini("golden_marker") or DEFAULT_MARKER)


def _baseline_dir(config: pytest.Config) -> Path:
    """The baseline directory, resolved against the pytest rootdir when relative."""
    raw = str(config.getini("golden_dir") or DEFAULT_DIR)
    path = Path(raw)
    return path if path.is_absolute() else config.rootpath / path


def _tolerances(config: pytest.Config) -> tuple[int, float, float]:
    """The configured ``(precision, rtol, atol)`` defaults for new baselines."""
    return (
        int(config.getini("golden_precision") or 10),
        float(config.getini("golden_rtol") or 1e-9),
        float(config.getini("golden_atol") or 1e-12),
    )


def pytest_configure(config: pytest.Config) -> None:
    """Register the golden marker so ``-m <marker>`` selects golden tests."""
    config.addinivalue_line(
        "markers",
        f"{_marker(config)}: capture the test's return value as a committed golden baseline.",
    )


@pytest.hookimpl(tryfirst=True)
def pytest_pyfunc_call(pyfuncitem: pytest.Function) -> bool | None:
    """Run a golden-marked test ourselves and snapshot its return value.

    For a test carrying the golden marker, this calls the function, captures its
    return value, and records it (``--golden-update``) or compares it against the
    committed baseline (the default), then returns ``True`` so pytest does not call
    the function a second time. Non-golden tests are left untouched.

    Args:
        pyfuncitem: The pytest function item about to be called.

    Returns:
        ``True`` when the golden test was handled here, else ``None`` (defer to
        pytest's normal call).

    Raises:
        GoldenError: When the return value drifts from its baseline, or no baseline
            exists yet in compare mode.
    """
    config = pyfuncitem.config
    if pyfuncitem.get_closest_marker(_marker(config)) is None:
        return None

    testargs = {name: pyfuncitem.funcargs[name] for name in pyfuncitem._fixtureinfo.argnames}
    result = pyfuncitem.obj(**testargs)
    _snapshot(pyfuncitem, result)
    return True


def _snapshot(pyfuncitem: pytest.Function, value: Any) -> None:
    """Record or compare *value* (a test's return) against its committed baseline."""
    config = pyfuncitem.config
    module_file = pyfuncitem.module.__file__
    assert module_file is not None
    store = GoldenStore(module_baseline_path(_baseline_dir(config), Path(module_file).stem))

    key = derive_node_key(pyfuncitem.nodeid)
    pid = param_id(key)
    if pid is not None and looks_autogenerated(pid, auto_argnames(pyfuncitem)):
        warnings.warn(
            f"golden: parametrize id {pid!r} in {key!r} looks auto-generated (index-based) — "
            "snapshot keys shift if cases are reordered. Pin explicit ids= on the parametrize.",
            GoldenIdWarning,
            stacklevel=3,
        )

    precision, rtol, atol = _tolerances(config)
    if config.getoption("--golden-update"):
        store.set(key, make_entry(value, precision=precision, rtol=rtol, atol=atol))
        store.save()
        return

    entry = store.get(key)
    if entry is None:
        raise GoldenError(
            f"golden: no baseline for {key!r}. Record it with `pytest --golden-update` "
            "and commit the baseline."
        )
    result = compare(value, entry)
    if not result.ok:
        raise GoldenError(f"golden: {key}\n  {result.detail}")
