"""Pytest plugin wiring the ``golden`` fixture + marker into any pyclawd project.

This generalises ``examples/golden_demo/conftest.py``: instead of a fixed demo
baseline location and a hard-coded ``blessed_on`` string, it loads the adopting
project's :class:`~pyclawd.project.Project` config and resolves everything from
its :class:`~pyclawd.project.GoldenConfig` — the baseline directory, the marker
name, and the version stamped onto freshly recorded baselines.

The plugin is loaded explicitly by ``pyclawd golden`` via
``pytest -p pyclawd.pytest_plugin``; it is intentionally **not** registered as a
``pytest11`` entry point, so adopting pyclawd needs no editable reinstall and the
fixture never activates in projects that did not ask for it.

Doctrine (see :mod:`pyclawd.golden`): tolerance is the gate, the hash is only a
fast path; *agents compare, humans bless*. Gate mode (the default) compares each
snapshot against its committed baseline and fails on drift; update mode
(``PYCLAWD_GOLDEN_UPDATE=1``, what ``pyclawd golden update`` sets) records fresh
baselines for a human to review and commit.

Limitation (v1): the per-snapshot tolerances from
:class:`~pyclawd.project.GoldenConfig` (``precision`` / ``rtol`` / ``atol``) are
**not** threaded into every ``golden(...)`` call. Each call uses the
:class:`~pyclawd.golden.Recorder` defaults unless the test passes explicit
``precision=`` / ``rtol=`` / ``atol=`` overrides (which win). Wiring the config
defaults through as the per-call fallback is left for a later revision.
"""

from __future__ import annotations

import os
import warnings
from collections.abc import Iterable, Iterator
from pathlib import Path

import pytest

import pyclawd
from pyclawd.discovery import ConfigError, load_project
from pyclawd.golden import GoldenStore, Recorder, module_baseline_path

#: Fallback marker name when no project / golden config is available.
DEFAULT_MARKER = "golden"


class GoldenIdWarning(UserWarning):
    """A golden snapshot key is built from an auto-generated parametrize id.

    Index-based ids (e.g. ``algorithm0``) silently shift when parametrize cases
    are added or reordered, which would orphan committed baselines. Emitted as a
    nudge to pin explicit ``ids=`` on the parametrize.
    """


def derive_node_key(nodeid: str) -> str:
    """Derive the snapshot key prefix from a pytest node id.

    The last ``::``-separated segment is the test function name plus any
    parametrization ``[param]`` suffix, which is exactly the stable per-case key
    the :class:`~pyclawd.golden.Recorder` expects.

    Args:
        nodeid: The pytest node id (e.g. ``tests/test_x.py::test_f[zdt1-de]``).

    Returns:
        The function name including any ``[param]`` suffix.
    """
    return nodeid.split("::")[-1]


def param_id(node_key: str) -> str | None:
    """Extract the bracketed parametrization id from a node key, if any.

    Args:
        node_key: A key from :func:`derive_node_key`.

    Returns:
        The text inside ``[...]`` (e.g. ``"zdt1-de"``), or ``None`` for a
        non-parametrized test.
    """
    if "[" not in node_key:
        return None
    return node_key.split("[", 1)[1].rsplit("]", 1)[0]


def _argnames_from_spec(spec: object) -> list[str]:
    """Normalise a parametrize argname spec into individual argnames.

    The first positional arg of a ``parametrize`` mark is either a comma-joined
    string (``"a,b"``) or a sequence of names (``["a", "b"]``).

    Args:
        spec: The ``mark.args[0]`` argname spec.

    Returns:
        The individual argnames (stripped, empties dropped).
    """
    if isinstance(spec, str):
        return [name.strip() for name in spec.split(",") if name.strip()]
    if isinstance(spec, (list, tuple)):
        return [str(name).strip() for name in spec if str(name).strip()]
    return []


def auto_argnames(node: pytest.Item) -> set[str]:
    """Argnames whose ids pytest may auto-number for this test node.

    Only ``parametrize`` marks that did **not** supply an explicit ``ids=`` can
    produce the fragile ``<argname><index>`` id form; a mark with ``ids=`` owns
    its ids, so its argnames are excluded. This is what lets the guardrail tell
    an auto ``algorithm0`` from an explicit ``s2`` / ``nsga2``.

    Args:
        node: The running pytest item.

    Returns:
        Argnames eligible for auto-numbered ids.
    """
    names: set[str] = set()
    for mark in node.iter_markers("parametrize"):
        if mark.kwargs.get("ids") is not None:
            continue
        if mark.args:
            names.update(_argnames_from_spec(mark.args[0]))
    return names


def looks_autogenerated(pid: str, argnames: Iterable[str]) -> bool:
    """Whether a parametrize id was index-based / pytest-auto-generated.

    Pytest falls back to ``<argname><index>`` (e.g. ``algorithm0``) when a
    parameter value has no readable id and no explicit ``ids=`` was given. Such
    ids are positional and fragile as snapshot keys. A segment is flagged only
    when it is exactly one of *argnames* followed by a run of digits — so an
    explicit id whose text merely ends in a digit (``zdt1``, ``nsga2``, ``s2``)
    is **not** flagged, because its prefix is not a parametrize argname.

    Args:
        pid: The parametrization id (the text between ``[`` and ``]``).
        argnames: The argnames eligible for auto-numbering (see
            :func:`auto_argnames`).

    Returns:
        ``True`` if any ``-``-separated segment is an ``<argname><digits>``.
    """
    argset = set(argnames)
    if not argset:
        return False
    for seg in pid.split("-"):
        for name in argset:
            tail = seg[len(name) :]
            if seg.startswith(name) and tail.isdigit():
                return True
    return False


def _resolve_marker() -> str:
    """Resolve the golden marker name from the project, defensively.

    Returns:
        The project's ``GoldenConfig.marker`` when a pyclawd project with a
        golden config can be loaded, else :data:`DEFAULT_MARKER`. Never raises —
        a missing/broken config degrades to the default so collection is never
        blocked in a non-pyclawd or golden-less project.
    """
    try:
        project = load_project()
    except ConfigError:
        return DEFAULT_MARKER
    if project is None or project.golden is None:
        return DEFAULT_MARKER
    return project.golden.marker


def pytest_configure(config: pytest.Config) -> None:
    """Register the golden marker so ``-m <marker>`` selects the oracle tier.

    Args:
        config: The pytest config being initialised.
    """
    marker = _resolve_marker()
    config.addinivalue_line("markers", f"{marker}: behavior-regression snapshot test.")


@pytest.fixture
def golden(request: pytest.FixtureRequest) -> Iterator[Recorder]:
    """Yield the per-test snapshot recorder bound to this project's baselines.

    Resolves the adopting project's config, locates the per-module baseline file
    under ``GoldenConfig.baseline_dir``, derives the snapshot key from the node
    id, and hands back a :class:`~pyclawd.golden.Recorder` in gate mode (or
    update mode when ``PYCLAWD_GOLDEN_UPDATE=1``). On teardown the store is saved
    only in update mode.

    Args:
        request: The pytest fixture request (gives the node id and module path).

    Yields:
        A :class:`~pyclawd.golden.Recorder` for the running test.

    Raises:
        Failed: Via :func:`pytest.fail` when the project has no golden config.
    """
    project = load_project()
    if project is None or project.golden is None:
        pytest.fail("golden not configured — add GoldenConfig to .pyclawd/config.py")

    baseline_dir = project.path(project.golden.baseline_dir)
    module_stem = Path(request.node.module.__file__).stem
    store = GoldenStore(module_baseline_path(baseline_dir, module_stem))

    node_key = derive_node_key(request.node.nodeid)
    pid = param_id(node_key)
    if pid is not None and looks_autogenerated(pid, auto_argnames(request.node)):
        warnings.warn(
            f"golden: parametrize id {pid!r} in {node_key!r} looks auto-generated "
            "(index-based) — snapshot keys shift if cases are reordered. "
            "Pin explicit ids= on the parametrize.",
            GoldenIdWarning,
            stacklevel=2,
        )

    update = os.environ.get("PYCLAWD_GOLDEN_UPDATE") == "1"
    blessed_on = project.pyclawd_version or pyclawd.__version__
    recorder = Recorder(store, node_key, update=update, blessed_on=blessed_on)
    yield recorder
    if update:
        store.save()
